filter:
    paths:
        - src/main/java/
    excluded_paths:
        - test/*
checks:
    javascript: true
    java:
        code_rating: true
build:
    nodes:
        analysis:
            environment:
                docker:
                    remote_engine: true
            tests:
                override:
                    - java-scrutinizer-run
                    - js-scrutinizer-run

        tests: true
